security:
  providers:
    account_manager:
      id: App\Auth\Infrastructure\AccountManager\Provider\AccountManagerUserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: account_manager
      form_login:
        login_path: app.auth.redirect-to-iam
      logout:
        path: app.auth.sign-out
        target: app.auth.signed-out
  access_control:
    - { path: ^/(%app.supported_locale%)/auth/redirect, roles: PUBLIC_ACCESS }
    - { path: ^/(%app.supported_locale%)/auth/catch, roles: PUBLIC_ACCESS }
    - { path: ^/(%app.supported_locale%)/auth/signed-out, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
