services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ghcr.io/at-cloud-pro/warehouse-app:${APP_VERSION:-0.1.1}
    depends_on:
      database:
        condition: service_healthy
  database:
    image: 'mysql:8.2.0'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "warehouse-app"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
