parameters:
  account_manager.host: '%env(AT_CLOUD_IAM_HOST)%'
  account_manager.service_id: '%env(AT_CLOUD_IAM_SERVICE_ID)%'
  account_manager.service_name: '%env(AT_CLOUD_IAM_SERVICE_NAME)%'
  app.supported_locale: 'en|pl'
  app.default_locale: 'en'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Auth\Domain\AccountManagerConfiguration:
    arguments:
      - '%account_manager.host%'
      - '%account_manager.service_id%'
      - '%account_manager.service_name%'
