parameters:
  account_manager.host: '%env(AT_CLOUD_ACCOUNT_MANAGER_HOST)%'
  account_manager.service: '%env(AT_CLOUD_ACCOUNT_MANAGER_SERVICE)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Auth\Infrastructure\AccountManager\Provider\AccountManagerUrlProvider:
    arguments:
      - '%account_manager.host%'
      - '%account_manager.service%'
